### ISSUE TITLE
Handling field conflicts

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/pg-simplify-inflector#1]
https://github.com/graphile-contrib/pg-simplify-inflector#handling-field-conflicts

@benjie instead of having conflicting fields why not just create a union type that can then be extracted using an inline fragment?

**Comment by benjie** [comment]
Because they might both exist (e.g. a post can have both an author and an editor).

Actually that copy is wrong it turns out (I released a new major version), one will be called “author” and the other “editor” now so conflicts are less likely.

**Comment by lifeiscontent** [comment]
@benjie in my case, we've got a recursive table lookup

```
Backward relation (connection) for constraint "roles_parent_id_fkey" on table "roles_public"."roles". To rename this relation with smart comments:

          COMMENT ON CONSTRAINT "roles_parent_id_fkey" ON "roles_public"."roles" IS E'@foreignFieldName newNameHere';
```

how would you suggest handling this? just call it parentRoles?

**Comment by lifeiscontent** [comment]
@benjie or is the version you're talking about not published? because I seem to have a lot of conflicts.

**Comment by benjie** [comment]
README updated.
