### ISSUE TITLE
Adding list suffix results in incorrect name

### ISSUE THREAD

**Issue by Coobaha** [graphile/pg-simplify-inflector#10]
version 3.0.0

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "cmFields-list" does not.

**Comment by benjie** [comment]
Hah; great spot.

This:
https://github.com/graphile-contrib/pg-simplify-inflector/blob/5f9ee454687787d6994e2f43cfbc4d0d863e3818/index.js#L177-L184

needs wrapping in `this.camelCase(...)`

Do you want to contribute a PR?

**Comment by Coobaha** [comment]
@benjie sure, will do

**Comment by benjie** [comment]
Awesome 🙏

**Comment by Coobaha** [comment]
#11
