### ISSUE TITLE
handling field conflict

### ISSUE THREAD

**Issue by shredmaster** [graphile/pg-simplify-inflector#12]
in additional to using smart comment on the constraint
comment on constraint "beverages_distributor_id_fkey" on "beverages" is
  E'@foreignFieldName distributedBeverages';

can we also support smart comment on the field level? 
comment on column beverages.distributor_id is '@foreignFieldName distributedBeverages';

**Comment by benjie** [comment]
As a shortcut for single-key relations? That seems a reasonable idea, but what would we call the forward relation part on the same column? Maybe the smart comment should be slightly different, e.g. “relationFieldName” / “relationForeignFieldName”?

**Comment by mateo2181** [comment]
I need to add a smart comment to use "products" instead of "productsByCategoryId" in the relationship one to many. Where I should add that comment? directly in postgres?

I have two tables:
products
- name
- categoryId

categories
  - name

I am trying this:
COMMENT ON CONSTRAINT "productos_categoriaId_fkey" on productos is 'categoria' .
but not works.

**Comment by benjie** [comment]
You’re almost there; change the `’categoria’` to `’@foreignFieldName products’` (but watch out for the smart quotes my phone added - sorry)

**Comment by mateo2181** [comment]
Yes, I have tried that, but the response is always the same and don't works.
This is the query that I run in pg Admin.
![Screenshot (1)](https://user-images.githubusercontent.com/12451246/54823449-a8a19080-4c86-11e9-80db-ae4c9b57234c.png)

And this is my query in Graphiql.
![Screenshot (2)](https://user-images.githubusercontent.com/12451246/54823497-ca027c80-4c86-11e9-9f52-7ffcffe1fc5c.png)

**Comment by benjie** [comment]
In the second query you’re querying productosCategorias (not productos) so I’d expect constraint named something like productos_categorias_categoryId_fkey

**Comment by mateo2181** [comment]
But there is not constraint on productosCategorias table, because the fk is on productos table.

**Comment by mateo2181** [comment]
I have restarted the server and works. 
Thanks!
