### ISSUE TITLE
Consider making primary key fetchers/updaters shorter

### ISSUE THREAD

**Issue by benjie** [graphile/pg-simplify-inflector#16]
Since they're the primary keys, listing them out seems kind of unnecessary. If people use database identifiers more than global node IDs (especially if they've disabled the node plugin!) then just having `myTable` be the default single fetcher, and `updateMyTable` update it makes sense.

i.e.:

- `user` -> `userByNodeId`
- `userById` -> `user`
- `updateUser` -> `updateUserByNodeId`
- `updateUserById` -> `updateUser`

Maybe make it an option.

Maybe change compound primary keys from `userByOrganizationAndIdentifier` to `userByPk` or similar.

**Comment by benjie** [comment]
Ref: https://github.com/graphile/postgraphile/issues/974

**Comment by benjie** [comment]
![screenshot 2019-01-24 18 46 31](https://user-images.githubusercontent.com/129910/51701025-6b16e300-2008-11e9-8bdb-a156f64a96ae.png)

Looks like this could go down well 👍

**Comment by zackkrida** [comment]
Was just checking the README for this—would be a great feature.

**Comment by benjie** [comment]
Added in https://github.com/graphile-contrib/pg-simplify-inflector/commit/529d0fafedb9e2a621d2796fbb563ebc35f936b0 and https://github.com/graphile-contrib/pg-simplify-inflector/commit/9bffaa064f68a275e37f1a8260c50800081ae9b4
