### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by kadaan** [graphile/pg-simplify-inflector#17]
Is there a minimum type definition that can be added to allow this to easily work with the rest of postgraphile via TypeScript?

**Comment by benjie** [comment]
Yeah, I can't remember the syntax off-hand but basically the type of `module.exports` is `Plugin`, where `import { Plugin } from 'graphile-build'`. Pretty sure that's all you need.

**Comment by kadaan** [comment]
I ended up doing: 
```typescript
declare module '@graphile-contrib/pg-simplify-inflector' {
  import { Plugin, SchemaBuilder, Options } from 'graphile-build';
  export default function PgSimplifyInflectorPlugin(builder: SchemaBuilder, options: Options): Promise<void> | void;
}
```
