### ISSUE TITLE
Using pgSimpleCollections: 'only' without pgOmitListSuffix: true will throw error

### ISSUE THREAD

**Issue by andreechristian** [graphile/pg-simplify-inflector#18]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

4.3.3

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE "user" (
 id serial PRIMARY KEY
);

CREATE TABLE photo (
 id serial PRIMARY KEY,
 url TEXT
);

CREATE TABLE user_photo (
 user_id integer references "user"(id),
 photo_id integer references "photo"(id),
 PRIMARY KEY (user_id, photo_id)
);
```

Steps to reproduce:

Current behavior:
Use `PgSimplifyInflectorPlugin` in conjunction with `simpleCollections: 'only'` **without** `graphileBuildOptions: { pgOmitListSuffix: true }` will throw error:
`Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "userPhotos-list" does not.`
Expected behavior:
It shouldn't throw error.

**Comment by benjie** [comment]
This is a bug that used to exist; but was fixed in https://github.com/graphile-contrib/pg-simplify-inflector/pull/11/files - it should be fixed in the v4 alpha.

**Comment by benjie** [comment]
What version of the simplify plugin are you running?

**Comment by andreechristian** [comment]
```
"@graphile-contrib/pg-simplify-inflector": "^3.0.0",
"pg": "^7.8.1",
"postgraphile": "^4.3.3",
"reflect-metadata": "^0.1.10",
```

**Comment by benjie** [comment]
Fixed on master; new release going out soon. PR welcome for 3.x
