### ISSUE TITLE
Using alongside postgraphile-plugin-connection-filter

### ISSUE THREAD

**Issue by AlexGustafsson** [graphile/pg-simplify-inflector#19]
I'm trying to use both this plugin and [postgraphile-plugin-connection-filter](https://github.com/graphile-contrib/postgraphile-plugin-connection-filter) but unfortunately
it doesn't work.

Using `postgraphile --append-plugins postgraphile-plugin-connection-filter` I get the expected functionality via i.e. `allUsers(filter: ...)`. Using `postgraphile --append-plugins @graphile-contrib/pg-simplify-inflector` I get the expected functionality via i.e. `users`. But using both plugins yields only `users` without any access to the filter option.

I've looked through the issues here as well as on the other package, but I haven't found a similar issue.

I'm posting this here since I assume it's more likely the issue lies here (since the package is renaming things) rather than the opposite.

PS. I'm using 4.0.0-alpha.0 of the inflector plugin, 1.0.0-rc.1 of the filter plugin and 4.3.3 of PostGraphile itself.

**Comment by benjie** [comment]
I can't reproduce this issue Alex:

```
mkdir clean && cd clean
yarn add postgraphile @graphile-contrib/pg-simplify-inflector postgraphile-plugin-connection-filter
npx postgraphile --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-simplify-inflector -c pggql_test -s a,b,c
```

```graphql
{
  people(filter: {firstName: {equalTo: "John"}}) {
    nodes {
      name
    }
  }
}
```

```json
{
  "data": {
    "people": {
      "nodes": [
        {
          "name": "John Smith"
        }
      ]
    }
  }
}
```

I don't think this is a bug; if you can give me steps to reproduce please re-open the issue.

**Comment by AlexGustafsson** [comment]
Thank you for taking your time. Seeing your code makes me realize my error. I had a space between plugins after `--append-plugins`, not a comma.

**Comment by benjie** [comment]
Ah 👍 We'll have to tighten down the CLI validation in v5 to catch issues like this.
