### ISSUE TITLE
Change log very out of date

### ISSUE THREAD

**Issue by ggascoigne** [graphile/pg-simplify-inflector#25]
Updating from ^4.0.0-alpha.0 to ^5.0.0-beta.1 is causing a lot of issues for me.  Even after adding pgShortPk: false, there are several interface differences that I wasn't expecting.

The docs don't really help much, and the changelog stops at v2.

I get that neither version was released per-se, but it would be nice if there was somewhere where I could find a clear list of breaking changes.

**Comment by benjie** [comment]
My advise would be: don’t update. This is not designed to be a module you update past major versions, it will break your schema in many ways. Pick a major version and stick to it.

If you’d like to send a PR updating the changelog that’d be very welcome.

**Comment by benjie** [comment]
Clarified in b02ff6aef6fa42b9cbc065d8bc65ca3fc2fae2f8
