### ISSUE TITLE
npm install -g for CLI use

### ISSUE THREAD

**Issue by asteinarson** [graphile/pg-simplify-inflector#26]
I got error/stacktrace from postgraphile when trying to install pg-simplify-injector in the terminal. I trued both `npm install --save` and `yarn add ` and the CLI would not start after either: 

`$ postgraphile -c postgres://user:pass@localhost:5432/db --append-plugins @graphile-contrib/pg-simplify-inflector --schema forum_example 
Failed to load plugin '@graphile-contrib/pg-simplify-inflector'
/usr/local/lib/nodejs/node-v10.15.3-linux-x64/lib/node_modules/postgraphile/build/postgraphile/cli.js:270
            throw e;
            ^
Error: Cannot find module '@graphile-contrib/pg-simplify-inflector'`

I am not inside a Node project or anything, just trying to use it as a CLI. 

After re-running the npm command with -g it worked: 

`npm install -g @graphile-contrib/pg-simplify-inflector `

The documentation then is slightly wrong here (it omits the -g flag).

**Comment by benjie** [comment]
Thanks for letting me know.

It's not recommended to install postgraphile or this package globally; in fact it's rarely the right thing to install any node package globally (there's a few limited exceptions, such as `yarn` and `neovim`). If you see any PostGraphile documentation saying to install with `-g` please let me know and I'll fix it.

If you install both `postgraphile` and `@graphile-contrib/pg-simplify-inflector` locally it should work :+1:

**Comment by asteinarson** [comment]
I see, good explanation. Thx.

**Comment by zaiste** [comment]
@benjie PostGraphile's [Quickstart Guide](https://www.graphile.org/postgraphile/quick-start-guide/#install-postgraphile) says to install with the `-g` option.

**Comment by benjie** [comment]
👍 We should probably add a note to say that you shouldn’t generally do that, but it’s probably still the right way for the quickstart.

**Comment by benjie** [comment]
Noted in https://github.com/graphile/graphile.github.io/commit/e932c19ac049c06b3c915693dec6169710838f19#diff-759bb801bc65e8097cf9baff202e460f
