### ISSUE TITLE
Lacking Typescript declarations

### ISSUE THREAD

**Issue by ab-pm** [graphile/pg-simplify-inflector#27]
Now that Postgraphile is properly typed, it complains about passing undeclared options… I guess the following should be added to `index.d.ts`:

	declare module 'graphile-build' {
		interface GraphileBuildOptions {
			/**
			* Set to true if you want simple collections to lose the 'List' suffix
			* (and connections to gain a 'Connection' suffix).
			*/
			pgOmitListSuffix: boolean;
			/**
			* Set to false if you want 'userPatch' instead of 'patch' in update
			* mutations.
			*/
			pgSimplifyPatch: boolean;
			/**
			* Set to false if you want 'allUsers' instead of 'users' at root level.
			*/
			pgSimplifyAllRows: boolean;
			/**
			* Set to true if you want primary key queries and mutations to have
			* `ById` (or similar) suffix; and the `nodeId` queries/mutations
			* to lose their `ByNodeId` suffix.
			*/
			pgShortPk: boolean;
		}
	}

I'm not exactly sure about the comments though, "*set to false*" is weird. Is there a `@default` annotation or something?

**Comment by benjie** [comment]
All those should be optional `pgSimplifyPatch?: boolean;`

I don't know about a `@default` annotation - have a look at the TSDoc docs :+1:

**Comment by benjie** [comment]
(Also the inflectors themselves need to have a `this: Inflector,` argument added as their first argument, python-style (otherwise `this` is treated as an `any`)

**Comment by ab-pm** [comment]
Ah, right, I forgot about making them optional because `PostGraphileOptions` has a `Partial<GraphileBuildOptions>` anyway.

**Comment by ab-pm** [comment]
Looks like TSDoc does [not yet](https://github.com/Microsoft/tsdoc/issues/27) support this, the RFC is already implemented by https://api-extractor.com/pages/tsdoc/tag_defaultvalue/ though

**Comment by benjie** [comment]
I'm going to close this as the TypeScript types won't be out until V5, and this repo is going to be moving to the graphile-engine monorepo as part of that and being rewritten into TypeScript so it'll become a redundant issue.
