### ISSUE TITLE
Document `foreignSimpleFieldName`

### ISSUE THREAD

**Issue by keithlayne** [graphile/pg-simplify-inflector#28]
I just spent a ton of time trying to work out how to do exactly what this smart tag does.  I'm super glad that the functionality exists, but it was difficult to discover.  I found it by reading the source (should have done that sooner) but that's not ideal.

Maybe a section on smart tags in the readme would be helpful.  I'll try to put together a PR when I have time.

**Comment by keithlayne** [comment]
In particular it seems to have different implications depending on the value of `pgOmitListSuffix`, so want to capture those interactions.

**Comment by benjie** [comment]
That'd be great, @keithlayne. :raised_hands:   Make sure you reference this with `Fixes #28` in the pull request issue description.

**Comment by keithlayne** [comment]
I should have saved you the work, my bad.  Thanks for doing all the things!
