### ISSUE TITLE
Primary keys that are also foreign keys not simplified

### ISSUE THREAD

**Issue by hgl** [graphile/pg-simplify-inflector#34]
### Summary
See the code snippet

### Steps to reproduce

Given this table design:

```
CREATE TABLE animal (
  id SERIAL PRIMARY KEY
);

CREATE TABLE cat (
  id integer PRIMARY KEY REFERENCES animal
);
```

### Expected results
An `animal` query should expose `cat`, a `cat` query should expose `animal`

### Actual results
An `animal` query exposes `catById`, a `cat` query exposes `animalById`

**Comment by benjie** [comment]
What happens if you rename `cat.id` to `cat.animal_id`?

**Comment by hgl** [comment]
Ah, renaming to `animal_id` fixes it, but it does make the `cat` query `cat(animalId: 10)` slightly awkward.

Feel free to close the issue if you think it works as intended.

**Comment by benjie** [comment]
Nah, just making sure I understand the issue. I think this warrants improvement :+1: It's going to need special handling.
