### ISSUE TITLE
Import problems from ESM to this module

### ISSUE THREAD

**Issue by innermatrix** [graphile/pg-simplify-inflector#41]
### Summary

Compiler errors (with a workaround) importing module from an ESM module. This issue affects both 6.x and 7.x alpha.

### Steps to reproduce

Create new ESM module and add this code to it

```
import PgSimplifyInflectorPlugin from '@graphile-contrib/pg-simplify-inflector';
import { createPostGraphileSchema } from 'postgraphile';

async function generateGraphQLSchema() {
	await createPostGraphileSchema('', 'app_public_v2', {
		appendPlugins: [PgSimplifyInflectorPlugin],
	});
}
```

Then run

```
npx tsc --noemit
```

### Expected results

No compiler error

### Actual results

Compiler error

```
test.ts:8:19 - error TS2322: Type 'typeof import("/Users/iris/Software/folx/test/b/node_modules/@graphile-contrib/pg-simplify-inflector/index")' is not assignable to type 'Plugin'.
  Type 'typeof import("/Users/iris/Software/folx/test/b/node_modules/@graphile-contrib/pg-simplify-inflector/index")' provides no match for the signature '(builder: SchemaBuilder, options: Options): void | Promise<void>'.

8   appendPlugins: [PgSimplifyInflectorPlugin],
                    ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in test.ts:8
```

### Additional context

This is due to package declaration problems outlined in 

* https://arethetypeswrong.github.io/?p=%40graphile-contrib%2Fpg-simplify-inflector%406.1.0
* https://arethetypeswrong.github.io/?p=%40graphile-contrib%2Fpg-simplify-inflector%407.0.0-alpha.1

### Possible Solution

Either add `export =` or switch this module from CJS to ESM in `package.json`

**Comment by benjie** [comment]
Either 1. use `PgSimplifyInflectorPlugin.default` in `appendPlugins` or 2. move to V5 where this isn't an issue (I think). Changing the `.d.ts` file is likely to break many people's applications.

**Comment by benjie** [comment]
(I made the changes in #42 but have closed it because they were meaningless.)

**Comment by innermatrix** [comment]
@benjie This is definitely a problem in v5 (that is where I first discovered it); see my links in "additional context" in the report above.

**Comment by benjie** [comment]
It shouldn't be; the V5 plugin (`@graphile/simplify-inflection`) works great for me and the type checker confirms it's correct:

https://arethetypeswrong.github.io/?p=%40graphile%2Fsimplify-inflection%408.0.0-beta.3

**Comment by innermatrix** [comment]
Oh looks like it got fixed after I reported; you’re right, the latest beta is fine. My bad.

**Comment by benjie** [comment]
I just checked and 8.0.0-0.2 published 8 months ago does not have this issue; it has never been an issue in V5 as far as I know:

https://arethetypeswrong.github.io/?p=%40graphile%2Fsimplify-inflection%408.0.0-0.2

**Comment by innermatrix** [comment]
Interesting. I have no idea how I ended up with a broken version then; my report was against a 7.x alpha and I have no idea why that landed in my deplist… but I’m sure it was some kind of fever dream trying to get our code ported to v5

**Comment by innermatrix** [comment]
anyhoo sorry for wasting your time!

**Comment by benjie** [comment]
No problem; I suspect you just tried to use the V4 plugin with V5. I did consider sticking with the V4 plugin name, but it's been annoying me for ages so it seemed a good point to "break" it with a new cleaner name.

Was there any parts of the V4->V5 migration that could have been made easier somehow (considering how much has changed)? I know there's still a lot of plugins that need porting... :sweat_smile:

**Comment by innermatrix** [comment]
> Was there any parts of the V4->V5 migration that could have been made easier somehow (considering how much has changed)? I know there's still a lot of plugins that need porting... 😅

TBD; I am still blocked on that schema generation bug I reported in Discord, and I need to test my lambda adapter; let's talk about that when I get something that at least somewhat works 🙂
