### ISSUE TITLE
[v5] `ById` suffix being added even when `pgShortPk` is true

### ISSUE THREAD

**Issue by Tam** [graphile/pg-simplify-inflector#44]
### Summary

The plugin is adding `ById` to queries even when `pgShortPk` is set to true. Setting it to false doesn't seem to have any effect.

I've also noticed that we have what are essentially duplicate mutations, but I'm not sure that's related to this plugin. Both mutations below use the ID of the user:

```graphql
updateUserById(input: UpdateUserByIdInput!): UpdateUserPayload
updateUser(input: UpdateUserInput!): UpdateUserPayload
```

### Steps to reproduce

Below is my `graphile.config.js` file:

```js
import { PostGraphileAmberPreset } from 'postgraphile/presets/amber';
import { makePgService } from 'postgraphile/adaptors/pg';
import { PostGraphileConnectionFilterPreset } from 'postgraphile-plugin-connection-filter';
import { PgSimplifyInflectionPreset } from '@graphile/simplify-inflection';
import { PgOmitArchivedPlugin } from '@graphile-contrib/pg-omit-archived';
import { PgManyToManyPreset } from '@graphile-contrib/pg-many-to-many';

const IS_DEV = process.env.NODE_ENV === 'dev';

/** @var {GraphileConfig.Preset} preset */
const preset = {
    extends: [
        PostGraphileAmberPreset,
        PostGraphileConnectionFilterPreset,
        PgSimplifyInflectionPreset,
        PgManyToManyPreset,
    ],
    disablePlugins: [
        'QueryQueryPlugin',
        'RegisterQueryNodePlugin',
        'PgRowByUniquePlugin',
        'PgMutationPayloadEdgePlugin',
    ],
    plugins: [
        PgOmitArchivedPlugin,
    ],
    pgServices: [
        makePgService({
            connectionString: process.env.DATABASE_URL,
            schemas: ['public'],
        }),
    ],
    gather: {
        installWatchFixtures: IS_DEV,
        pgJwtTypes: 'public.jwt',
    },
    schema: {
        dontSwallowErrors: IS_DEV,
        pgForbidSetofFunctionsToReturnNull: true,
        pgJwtSecret: process.env.JWT_SECRET,
        exportSchemaSDLPath: IS_DEV ? `${process.cwd()}/schema.graphql` : void 0,
        defaultBehavior: '+list',

        pgOmitListSuffix: true,
        pgShortPk: true,
    },
    grafast: {
        explain: IS_DEV,
    },
    grafserv: {
        watch: IS_DEV,
        graphiql: IS_DEV,
        graphiqlOnGraphQLGET: IS_DEV,
    },
};

export default preset;
```

### Expected results

Assuming a single public users table: 

```graphql
user(id: ID!): User
users(...): [User!]
usersConnection(...): UserConnection
```

### Actual results

```graphql
userById(id: ID!): User
users(...): [User!]
usersConnection(...): UserConnection
```

### Additional context

Node: 21-alpine3.18
Postgres: 15

```json
"dependencies": {
  "@dataplan/json": "0.0.1-beta.22",
  "@dataplan/pg": "0.0.1-beta.24",
  "@graphile-contrib/pg-many-to-many": "2.0.0-beta.3",
  "@graphile-contrib/pg-omit-archived": "v4.0.0-beta.3",
  "@graphile/simplify-inflection": "8.0.0-beta.5",
  "express": "^4.19.2",
  "graphile-build": "5.0.0-beta.23",
  "graphile-build-pg": "5.0.0-beta.27",
  "graphile-worker": "0.16.6",
  "postgraphile": "5.0.0-beta.28",
  "postgraphile-plugin-connection-filter": "v3.0.0-beta.3"
}
```

### Possible Solution

Not a solution, but it might have something to do with me disabling `PgRowByUniquePlugin`. If I re-enable it the schema looks like:

```graphql
user(userId: ID!): User
userById(id: ID!): User
users(...): [User!]
usersConnection(...): UserConnection
```

But it could be that all it's doing is adding the `user(userId)` query.

**Comment by Tam** [comment]
I should add that the table doesn't have an `id` column so that's likely to also be causing issues.

```sql
create table if not exists public.user (
  account_id uuid primary key references private.account (id) on delete cascade not null
, name varchar
, preferred_name varchar
);
```

Update: And from the logs `Plugin 'PgSimplifyInflectionPlugin' attempted to overwrite inflector 'rowByUnique', but no such inflector exists.`

**Comment by benjie** [comment]
You’re skipping the row by unique plugin so the row by primary key accessors are not added to the schema, hence the warning. You want pgShortPk to be false since you’re only using the Node accessors, not primary key accessors. You should also consider using the relay preset which shapes the schema in the way it looks like you’re trying for. I don’t know how you have managed to get duplicate `: ID!` accessors but I’m going to assume that’s a typo in your code block.

**Comment by Tam** [comment]
Thanks, I actually wanted to get away from the relay stuff and ended up getting what roughly what I was after (a very minimal schema) by disabling the `NodePlugin` instead! Still not sure how I ended up with duplicate `ID` queries.
